// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSMaUeiCCxFr7_lJL6OW-ubRP33NWy5Wc',
    appId: '1:689933184697:web:9ebe0601beb5a792db3568',
    messagingSenderId: '689933184697',
    projectId: 'redteso',
    authDomain: 'redteso.firebaseapp.com',
    storageBucket: 'redteso.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkN1jsvz9_bBaRvtFq8Yd2c140Tet-pNs',
    appId: '1:689933184697:android:46f158472bbbfa85db3568',
    messagingSenderId: '689933184697',
    projectId: 'redteso',
    storageBucket: 'redteso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUjB648wxdyJRo9KDIhzenjLh148SNAA',
    appId: '1:689933184697:ios:ecbc216e1d5ca695db3568',
    messagingSenderId: '689933184697',
    projectId: 'redteso',
    storageBucket: 'redteso.firebasestorage.app',
    iosBundleId: 'com.example.redTeso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgUjB648wxdyJRo9KDIhzenjLh148SNAA',
    appId: '1:689933184697:ios:ecbc216e1d5ca695db3568',
    messagingSenderId: '689933184697',
    projectId: 'redteso',
    storageBucket: 'redteso.firebasestorage.app',
    iosBundleId: 'com.example.redTeso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSMaUeiCCxFr7_lJL6OW-ubRP33NWy5Wc',
    appId: '1:689933184697:web:16cd5f6a46582409db3568',
    messagingSenderId: '689933184697',
    projectId: 'redteso',
    authDomain: 'redteso.firebaseapp.com',
    storageBucket: 'redteso.firebasestorage.app',
  );
}
